routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


/**
 * Route model bindings
 */
Route::model('book', App\Models\Book::class);

/**
 * Book resource routes
 */
Route::get('/books/search', 'BookController@search')->name('books.search');
Route::post('/books/{book}', 'BookController@update')->name('books.update');
Route::get('/books/{book}/destroy', 'BookController@destroy')->name('books.destroy'); // added /delte to fix because I can't have routes with the same enpoint, I know it's ugly but is too late
Route::resource('books', 'BookController', ['except' => ['update', 'destroy']]);

resources/views/includes/errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/includes/footer.blade.php
<div id="copyright text-right">© Copyright 2013 Scotchy Scotch Scotch</div>

resources/views/includes/head.blade.php
@section('meta')
    <meta charset="utf-8">
@stop

@section('style')
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-modal/2.2.6/css/bootstrap-modal.css">
    {{-- <link rel="stylesheet" href="{{ mix('css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ mix('css/bootstrap-theme.css') }}"> --}}
@show

resources/views/includes/header.blade.php
<div class="header clearfix">
    <h3 class="text-muted pull-left">Library App</h3>
    <a type="button" class="btn btn-primary pull-right" href="{{ route('books.index') }}">Books</a>
    <a type="button" class="btn btn-primary pull-right" href="{{ route('books.create') }}">Add Book</a>
</div>

resources/views/includes/modal.blade.php
<!-- Modal -->
<div class="modal" id="model-{{ $book->id }}" tabindex="" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Set <strong>{{$book->name}}</strong> status to not available?</h4>
      </div>
      {{-- <div class="modal-body">
      {{$book->name}}
    </div> --}}
    <div class="modal-footer">
      <button type="button" class="btn btn-default" >Set to Available</button>
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  </div>
  <!-- /.modal-content -->
</div>
<!-- /.modal-dialog -->
</div>
<!-- /.modal -->

resources/views/includes/scripts.blade.php
@section('scripts')

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.js"></script>
    <script src="{{ mix('js/app.js') }}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-modal/2.2.6/js/bootstrap-modal.js"></script>

    <script>
        $('.datepicker').datepicker();

        $('[id^=model]').click(function(){
            this;
            $(this);
        });
    </script>
@show